"""contacts db edit

Revision ID: fbf7bf1ff5aa
Revises: ca56e17640d3
Create Date: 2026-03-01 17:24:26.769984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbf7bf1ff5aa'
down_revision: Union[str, Sequence[str], None] = 'ca56e17640d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacs_email'), table_name='contacs')
    op.drop_index(op.f('ix_contacs_id'), table_name='contacs')
    op.drop_index(op.f('ix_contacs_name'), table_name='contacs')
    op.drop_index(op.f('ix_contacs_phone'), table_name='contacs')
    op.drop_table('contacs')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('contacts_pkey'))
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('contacs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('contacs_pkey'))
    )
    op.create_index(op.f('ix_contacs_phone'), 'contacs', ['phone'], unique=True)
    op.create_index(op.f('ix_contacs_name'), 'contacs', ['name'], unique=False)
    op.create_index(op.f('ix_contacs_id'), 'contacs', ['id'], unique=False)
    op.create_index(op.f('ix_contacs_email'), 'contacs', ['email'], unique=True)
    # ### end Alembic commands ###
